# Generated by Django 4.1.1 on 2022-09-25 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replie_content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=100)),
                ('likes', models.IntegerField()),
                ('saves', models.IntegerField()),
                ('replies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.replies')),
            ],
        ),
    ]
