# Generated by Django 4.1.1 on 2022-09-25 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tweet',
            new_name='FeedContent',
        ),
    ]
