# Generated by Django 4.1.1 on 2022-09-26 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
        ('feed', '0002_rename_tweet_feedcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedcontent',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topics.topics'),
        ),
    ]
