# Generated by Django 4.1.1 on 2022-09-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_feedcontent_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedcontent',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedcontent',
            name='saves',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
