# Generated by Django 4.1.1 on 2022-09-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_alter_feedcontent_likes_alter_feedcontent_saves'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedcontent',
            name='shares',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
