# Generated by Django 4.1.1 on 2022-09-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
        ('feed', '0006_feedcontent_shares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedcontent',
            name='topic',
        ),
        migrations.AddField(
            model_name='feedcontent',
            name='topic',
            field=models.ManyToManyField(to='topics.topics'),
        ),
    ]
