# Generated by Django 4.1.1 on 2022-10-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_feedcontent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedcontent',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
