# Generated by Django 4.1.1 on 2022-10-06 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
        ('feed', '0010_feedcontent_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedcontent',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topic', to='topics.topics'),
        ),
    ]
