# Generated by Django 4.1.1 on 2022-10-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_rename_feedcontent_feeds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds',
            name='content',
            field=models.CharField(max_length=10000),
        ),
    ]
