# Generated by Django 4.1.1 on 2022-10-06 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0013_alter_feeds_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replies',
            options={'ordering': ['-like']},
        ),
        migrations.RenameField(
            model_name='replies',
            old_name='replie_content',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='replies',
            name='commentated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='replies',
            name='commentator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='replies',
            name='like',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
