# Generated by Django 4.1.1 on 2022-10-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='comment',
            field=models.CharField(max_length=2000),
        ),
    ]
