# Generated by Django 4.1.1 on 2022-10-09 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0018_alter_replies_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeds',
            name='likes',
        ),
        migrations.AddField(
            model_name='feeds',
            name='likes',
            field=models.ManyToManyField(related_name='like_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
