# Generated by Django 4.1.1 on 2022-10-10 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0019_remove_feeds_likes_feeds_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeds',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Likess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('liked', 'liked'), ('unliked', 'unliked')], max_length=15)),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.feeds')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
