# Generated by Django 4.1.1 on 2022-10-10 10:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0020_feeds_liked_likess'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likess',
            new_name='Votes',
        ),
    ]
