# Generated by Django 4.1.1 on 2022-10-10 11:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0021_rename_likess_votes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feeds',
            new_name='Feed',
        ),
    ]
