# Generated by Django 4.1.1 on 2022-10-11 05:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0023_remove_feed_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='likes',
            field=models.ManyToManyField(related_name='related_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
