# Generated by Django 4.1.1 on 2022-10-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0024_alter_feed_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
