# Generated by Django 4.1.1 on 2022-10-13 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0025_feed_liked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Votes',
        ),
    ]
