# Generated by Django 4.1.1 on 2022-10-13 03:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0026_delete_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='saves',
        ),
        migrations.AddField(
            model_name='feed',
            name='saves',
            field=models.ManyToManyField(related_name='related_save', to=settings.AUTH_USER_MODEL),
        ),
    ]
