# Generated by Django 4.1.1 on 2022-10-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0030_alter_feed_likes_alter_feed_saves'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='devcom'),
        ),
    ]
