# Generated by Django 4.1.2 on 2022-10-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0031_feed_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='viewes',
            field=models.IntegerField(default=0),
        ),
    ]
